### ISSUE TITLE
Post subscribers to list - unknown parameter ConsentToTrack

### ISSUE THREAD

**Issue by AlinChindea** [nufyoot/createsend-node#24]
Hi there,

I have tried to post new subscribes to a list using the node.js wrapper and kept getting `unknown parameter ConsentToTrack`. This would happen every time I pass a value to the key `ConsentToTrack`. If I leave the value as an empty string, the POST call succeeds but that's of no use for me as I need to track users. Anyhow, I've contacted Campaign Monitor and this was their reply: 

> In the last few months we updated our API to v 3.2, and as such, all of our own wrappers were updated as well: https://www.campaignmonitor.com/api/wrappers/ However, as you can see there, we don't actually manage the Node wrapper solution, so it's most likely not been updated to v3.2, which would mean it doesn't support the newer Consent to Track field. You'd either need to use one of our own supported wrappers, or manage that consent to track field in app or via list imports.

This is the code I was using: 

`const createsend = require('createsend-node');
const auth = { apiKey: 'api-key'};
const api = new createsend(auth);

const userName = user_first_name;
const userEmail = user_email;
const listId = 'list-id'
const details = {
        EmailAddress: userEmail,
        Name: userName,
        "ConsentToTrack": "Unchanged"
    };
api.subscribers.addSubscriber(listId, details, (err, res) => {
        if (err) console.log(err);
        console.log(res);
    })`

Not sure it's an issue but worth flagging it here. Your feedback is much appreciated.

Alin

P.s. I got it working with the Python wrapper but I'd very much prefer node.js :D

**Comment by tolkienosborn** [comment]
Hi Alin, I know its an old post but i got it to work with node.js by upgrading the version in lib/createsend.js on line 30 to version: 'v3.2',

**Comment by AlinChindea** [comment]
Thank you, Tolkien. Sounds great and seems to do the trick. I'll close the issue. Cheers!

**Comment by raulir** [comment]
Sorry about posting to old ticket, but this is the only result in Google and maybe this helps someone.

So, I had the same problem, but with PHP.

Solution, if you can't update wrapper or you have custom code:

The root cause is that their old API stopped supporting this parameter.

Search your code for CM API URL and replace old URL (eg https://api.createsend.com/api/v3.1/) with new one: https://api.createsend.com/api/v3.2/

**Comment by sinan-evanshunt** [comment]
And I too just ran into this same error on Drupal 7. Turns out the library was old. Grabbed the latest from https://github.com/campaignmonitor/createsend-php and now I can see new entries on the lists. Thanks to @raulir for the tip.
